#! /bin/bash

x=$(dirname $0)

java -Xrunjmp:nomethods \
	-Xmx1024m \
	-cp ${x}/bin:${x}/../org.spoofax.aterm/aterm.jar:${x}/ext/jjtraveler-0.4.3.jar:${x}/ext/shared-objects-1.4.jar \
	org.spoofax.jsglr.Main $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 --wait-for-profiler

