#! /bin/bash

base=$(dirname $0)
jars=${base}/../share/java
fcp=""

if [ -e ${base}/AUTHORS ] ; then
	jars=${base}/lib
	fcp=${base}/build/spoofax-jsglr-0.2.0.jar
fi

cp="jjtraveler-0.4.3.jar junit-3.8.2.jar shared-objects-1.4.jar spoofax-aterm-0.2.1.jar spoofax-jsglr-0.2.0.jar"


for x in ${cp} ; do
	fcp="${fcp}:${jars}/${x}"
done

echo java \
	-Xmx1024m \
	-Xss10m \
	-cp ${fcp} \
	org.spoofax.jsglr.Main $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 >&2

java \
	-Xmx1024m \
	-Xss10m \
	-cp ${fcp} \
	org.spoofax.jsglr.Main $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12

